<a href="https://colab.research.google.com/github/micsupasun/university_of_essex/blob/main/data_science_and_decision_making/lab6_recommendation_movie/my_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# IMPORT LIBRARY

In [ ]:
import numpy as np
import pandas as pd

# IMPORT DATA  Load the data from ``jester-data-1.csv'',

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# The data is from http://eigentaste.berkeley.edu/dataset/ and it contains the ratings of 100 jokes from 11,190 users
df = pd.read_csv("/content/drive/MyDrive/essex_university/data_science_and_making_data_decition/lab6_recommendation_movie/jester-data-1.csv",header=None)
df

0      1      2      3      4     5      6     7     8      9    ...  \
0       74  -7.82   8.79  -9.66  -8.16 -7.52  -8.50 -9.85  4.17  -8.98  ...   
1      100   4.08  -0.29   6.36   4.37 -2.38  -9.66 -0.73 -5.34   8.88  ...   
2       49  99.00  99.00  99.00  99.00  9.03   9.27  9.03  9.27  99.00  ...   
3       48  99.00   8.35  99.00  99.00  1.80   8.16 -2.82  6.21  99.00  ...   
4       91   8.50   4.61  -4.17  -5.39  1.36   1.60  7.04  4.61  -0.44  ...   
...    ...    ...    ...    ...    ...   ...    ...   ...   ...    ...  ...   
24978  100   0.44   7.43   9.08   2.33  3.20   6.75 -8.79 -0.53  -8.74  ...   
24979   91   9.13  -8.16   8.59   9.08  0.87  -8.93 -3.50  5.78  -8.11  ...   
24980   39  99.00  99.00  99.00  99.00 -7.77  99.00  6.70 -6.75  99.00  ...   
24981   37  99.00  99.00  99.00  99.00 -9.71  99.00  4.56 -8.30  99.00  ...   
24982   72   2.43   2.67  -3.98   4.27 -2.28   7.33  2.33  4.56   6.75  ...   

         91     92     93     94     95     96     97     98     99     100  
0       2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1       2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2      99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3      99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4       5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  
...      ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
24978   8.83  -1.21   9.22  -6.70   8.45   9.03   6.55   8.69   8.79   7.43  
24979  -1.17  -5.73  -1.46   0.24   9.22  -8.20  -7.23  -8.59   9.13   8.45  
24980  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24981  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  
24982  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  99.00  

[24983 rows x 101 columns]

In [ ]:
# Ratings are real values ranging from -10.00 to +10.00 (the value "99" corresponds to "null" = "not rated").

# Check the dataset description to figure out which value you should replace with NaNs (the cells for which we don't have a rating). This is the test set.
# To replace values when you load, you can find help here: https://stackoverflow.com/questions/29247712/how-to-replace-a-value-in-pandas-with-nan
df = df.replace(99.00, np.nan)
df




0     1     2     3     4     5     6     7     8     9    ...   91   \
0       74.0 -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98  ...  2.82   
1      100.0  4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  ...  2.82   
2       49.0   NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN  ...   NaN   
3       48.0   NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  ...   NaN   
4       91.0  8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  ...  5.19   
...      ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  100.0  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  ...  8.83   
24979   91.0  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  ... -1.17   
24980   39.0   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN  ...   NaN   
24981   37.0   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN  ...   NaN   
24982   72.0  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 101 columns]

In [ ]:
# The first column(collum "0") gives the number of jokes rated by that user. 
# The next 100 columns give the ratings for jokes 01 - 100
# so delete collum "0" because don't contain rating

# There's a column you need to remove because it doesn't contain ratings. Check the description of the dataset and figure out which one. Then drop it.
df = df.drop(columns=[0])
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2       NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
3       NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN   NaN  ...   NaN   
24981   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN   NaN  ...   NaN   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 100 columns]

#  Use pandas to find the best- and the worst-rated jokes

In [ ]:
mean_each_movie = df.mean(axis=0)
mean_each_movie

1      0.904573
2      0.208460
3      0.316574
4     -1.449114
5      0.403556
         ...   
96     1.528003
97     1.673750
98     0.767692
99    -0.031244
100    1.354711
Length: 100, dtype: float64

In [ ]:
# the best-rate jokes movie
the_best_movie = mean_each_movie[mean_each_movie == max(mean_each_movie)]
the_best_movie

50    3.665085
dtype: float64

In [ ]:
# the worst-rate jokes movie
the_worst_movie = mean_each_movie[mean_each_movie == min(mean_each_movie)]
the_worst_movie

58   -3.83388
dtype: float64

In [ ]:
print("the best movie is:",the_best_movie.index.get_level_values(0)[0])
print("the worst movie is:",the_worst_movie.index.get_level_values(0)[0])

the best movie is: 50
the worst movie is: 58


Modify and use the helper function provided in the helper_function notebook (or create your own) to label 10% of the dataset cells that are not NaNs as 99. This is your validation set. Keep the the actual values of the cells so you can use them later (as done in the example of the helper_function notebook).

In [ ]:
# Modify and use the helper function provided in the helper_function notebook 
# (or create your own) to label 10% of the dataset cells that are not NaNs as 99. This is your validation set.
# Keep the the actual values of the cells so you can use them later (as done in the example of the helper_function notebook).

def replace(orig, percentage=0.1):
  """
  Replaces 'percentage'% of the original values in 'orig' with 99's
  :param orig: original data array
  :param percentage: percentage of values to replace (0<percentage<1)
  """
  new_data = orig.copy()
  # rated = np.where(arr!=99)
  rated = np.where(~np.isnan(orig))
  print("rated",rated)
  n_rated = len(rated[0])
  print("n_rated",n_rated)
  # random position ตำเเหน่งindex 1อาจไปอยู่99แต่เค่เปลี่ยนตำเเหน่งเฉยๆ
  idx = np.random.choice(n_rated, size=int(percentage*n_rated), replace=False)
  print("idx",idx)
  new_data[rated[0][idx], rated[1][idx]] = 99
  print((rated[0][idx], rated[1][idx]))
  return new_data, (rated[0][idx], rated[1][idx])

In [ ]:
arr = df.values
print(arr.shape)

(24983, 100)


In [ ]:
rated = np.where(~np.isnan(arr))
print(len(rated[0]), rated[1].shape)

1810455 (1810455,)


In [ ]:
new_arr, idx = replace(arr, 0.1)
new_arr

rated (array([    0,     0,     0, ..., 24982, 24982, 24982]), array([ 0,  1,  2, ..., 69, 70, 86]))
n_rated 1810455
idx [1667959 1607247 1487111 ... 1061817   36939  778211]
(array([23022, 22186, 20517, ..., 14711,   514, 10788]), array([ 4, 99,  9, ...,  8, 86, 68]))


array([[99.  ,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [ ]:
new_arr.shape,len(idx)

((24983, 100), 2)

In [ ]:
idx

(array([23022, 22186, 20517, ..., 14711,   514, 10788]),
 array([ 4, 99,  9, ...,  8, 86, 68]))

In [ ]:
arr

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [ ]:
arr[idx[0][0], idx[1][0]]

-9.66

In [ ]:
new_arr[idx[0][0], idx[1][0]]

99.0

In [ ]:
df

1     2     3     4     5     6     7     8     9     10   ...   91   \
0     -7.82  8.79 -9.66 -8.16 -7.52 -8.50 -9.85  4.17 -8.98 -4.76  ...  2.82   
1      4.08 -0.29  6.36  4.37 -2.38 -9.66 -0.73 -5.34  8.88  9.22  ...  2.82   
2       NaN   NaN   NaN   NaN  9.03  9.27  9.03  9.27   NaN   NaN  ...   NaN   
3       NaN  8.35   NaN   NaN  1.80  8.16 -2.82  6.21   NaN  1.84  ...   NaN   
4      8.50  4.61 -4.17 -5.39  1.36  1.60  7.04  4.61 -0.44  5.73  ...  5.19   
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
24978  0.44  7.43  9.08  2.33  3.20  6.75 -8.79 -0.53 -8.74  7.23  ...  8.83   
24979  9.13 -8.16  8.59  9.08  0.87 -8.93 -3.50  5.78 -8.11  4.90  ... -1.17   
24980   NaN   NaN   NaN   NaN -7.77   NaN  6.70 -6.75   NaN   NaN  ...   NaN   
24981   NaN   NaN   NaN   NaN -9.71   NaN  4.56 -8.30   NaN   NaN  ...   NaN   
24982  2.43  2.67 -3.98  4.27 -2.28  7.33  2.33  4.56  6.75  4.61  ...   NaN   

        92    93    94    95    96    97    98    99    100  
0       NaN   NaN   NaN   NaN   NaN -5.63   NaN   NaN   NaN  
1     -4.95 -0.29  7.86 -0.19 -2.14  3.06  0.34 -4.32  1.07  
2       NaN   NaN  9.08   NaN   NaN   NaN   NaN   NaN   NaN  
3       NaN   NaN  0.53   NaN   NaN   NaN   NaN   NaN   NaN  
4      5.58  4.27  5.19  5.73  1.55  3.11  6.55  1.80  1.60  
...     ...   ...   ...   ...   ...   ...   ...   ...   ...  
24978 -1.21  9.22 -6.70  8.45  9.03  6.55  8.69  8.79  7.43  
24979 -5.73 -1.46  0.24  9.22 -8.20 -7.23 -8.59  9.13  8.45  
24980   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24981   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
24982   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[24983 rows x 100 columns]

Use latent factor modeling (with 2 latent factors) to infer the hidden ratings of the users (they are labeled as "99" in the dataset) on the training set. You will have to modify at least one line in the provided sgd() function for this (and probably 2, depending on your variable names).

In [ ]:
n_latent_factors = 2

user_ratings = df.values
# Initialise as random values
latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))

In [ ]:
user_ratings.shape[0],user_ratings.shape[1]

(24983, 100)

In [ ]:
user_ratings

array([[-7.82,  8.79, -9.66, ...,   nan,   nan,   nan],
       [ 4.08, -0.29,  6.36, ...,  0.34, -4.32,  1.07],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       ...,
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [  nan,   nan,   nan, ...,   nan,   nan,   nan],
       [ 2.43,  2.67, -3.98, ...,   nan,   nan,   nan]])

In [ ]:
# 24983
latent_user_preferences

array([[0.8630607 , 0.68580671],
       [0.11322578, 0.69898274],
       [0.41713759, 0.88546544],
       ...,
       [0.06606305, 0.3873911 ],
       [0.91209877, 0.49030435],
       [0.15453229, 0.63397114]])

In [ ]:
# 100
latent_item_features

array([[0.15786495, 0.27084567],
       [0.77199163, 0.33575196],
       [0.52450449, 0.41007405],
       [0.70804541, 0.33734704],
       [0.24484451, 0.89091179],
       [0.00845837, 0.05346005],
       [0.60846773, 0.96394728],
       [0.63801731, 0.01156686],
       [0.70924962, 0.94860328],
       [0.37729098, 0.41523812],
       [0.77144668, 0.75306761],
       [0.90609946, 0.25872221],
       [0.83934362, 0.85085379],
       [0.30467381, 0.29275607],
       [0.53673134, 0.99375724],
       [0.36706455, 0.98360921],
       [0.79244806, 0.70463387],
       [0.86977661, 0.78838237],
       [0.39904175, 0.58695304],
       [0.78094735, 0.53040604],
       [0.96545581, 0.81697968],
       [0.58644839, 0.16613553],
       [0.17751986, 0.14691314],
       [0.65529258, 0.56552797],
       [0.67604161, 0.2597591 ],
       [0.96611858, 0.40046511],
       [0.91564332, 0.10737479],
       [0.17771478, 0.78950432],
       [0.09226464, 0.08440682],
       [0.49335704, 0.81426473],
       [0.

In [ ]:
def predict_rating(user_id, item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)


def train(user_id, item_id, rating, alpha=0.0001):
    #print(item_id)
    predicted_rating = predict_rating(user_id, item_id)
    err =  predicted_rating - rating
    #print(err)
    user_pref_values = latent_user_preferences[user_id]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err
    
# Use latent factor modeling (with 2 latent factors) to infer the hidden ratings of the users (they are labeled as "99" in the dataset) on the training set.
#  You will have to modify at least one line in the provided sgd() function for this (and probably 2, depending on your variable names).
def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                # if not np.isnan(rating):
                if rating != 99 and not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:\tMSE=%.6f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

In [ ]:
# Iterations in sgd will take a long time to run: you can (and should) use low numbers. Try something like 10.
import matplotlib.pyplot as plt
num_iter = 10
hist = sgd(num_iter)  # Note how the MSE decreases with the number of iterations
plt.figure()
plt.plot(np.arange(0, num_iter, 10000), hist)
plt.xlabel("Iterations")
plt.ylabel("MSE")
plt.show()
# You can interrupt at any point the execution of this function, because the values are updated in each iteration, 
# so if you interrupt execution you can use the latent_user_preferences and latent_item_features.
#  Calculate the performance (e.g., MSE) of the algorithm on the validation dataset


Iteration 0/10:	MSE=26.158151


KeyboardInterrupt: ignored

In [ ]:
#  Make predictions for the test dataset.
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[1.40066135, 0.65367311, 0.74313256, ..., 1.50293209, 0.43372318,
        2.12328825],
       [0.69854394, 0.31860172, 0.3240017 , ..., 0.64526309, 0.14722509,
        1.18025048],
       [1.52058368, 0.70235841, 0.76089674, ..., 1.5290139 , 0.40289347,
        2.42443082],
       ...,
       [0.3799425 , 0.17328182, 0.1761782 , ..., 0.35085444, 0.08000494,
        0.6420717 ],
       [1.27765061, 0.59902604, 0.69525688, ..., 1.40983973, 0.42140124,
        1.89156173],
       [0.94009321, 0.4323028 , 0.45828456, ..., 0.91815574, 0.23110196,
        1.53047487]])

In [ ]:
values = [zip(user_ratings[i], predictions[i]) for i in range(predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = df.columns
comparison_data

1                            2    \
0      (-7.82, 1.400661353920224)   (8.79, 0.6536731146989287)   
1      (4.08, 0.6985439386948117)  (-0.29, 0.3186017172948452)   
2       (nan, 1.5205836819655965)    (nan, 0.7023584106238829)   
3       (nan, 0.6203922539167297)   (8.35, 0.2928127366696211)   
4       (8.5, 1.3505797350062987)   (4.61, 0.6236170397725598)   
...                           ...                          ...   
24978  (0.44, 1.1100060225958912)   (7.43, 0.5173848637382203)   
24979  (9.13, 0.9668981786009865)  (-8.16, 0.4566078573732194)   
24980   (nan, 0.3799425003420739)   (nan, 0.17328182122870797)   
24981    (nan, 1.277650607320733)    (nan, 0.5990260436156103)   
24982  (2.43, 0.9400932064729951)   (2.67, 0.4323028026110188)   

                                3                             4    \
0       (-9.66, 0.7431325629124005)  (-8.16, -1.4318531201427687)   
1        (6.36, 0.3240017023074138)   (4.37, -0.8515680691158205)   
2         (nan, 0.7608967375899309)    (nan, -1.6896876669731957)   
3         (nan, 0.3498301104904866)    (nan, -0.5732368801586448)   
4       (-4.17, 0.6744637352245622)  (-5.39, -1.5047981357586089)   
...                             ...                           ...   
24978     (9.08, 0.584875204024561)   (2.33, -1.1466615279298706)   
24979    (8.59, 0.5468023027249754)   (9.08, -0.8887383859087575)   
24980    (nan, 0.17617819557937114)     (nan, -0.463316013361146)   
24981     (nan, 0.6952568783286057)    (nan, -1.2548253746960576)   
24982  (-3.98, 0.45828456387398897)   (4.27, -1.0804288664796973)   

                                5                            6    \
0       (-7.52, 0.7804854884575942)    (-8.5, 2.515972031150318)   
1        (-2.38, 0.446868468414124)  (-9.66, 1.2404002509438947)   
2        (9.03, 0.9039974937616136)    (9.27, 2.717241973384008)   
3         (1.8, 0.3201421987930283)   (8.16, 1.1207709834911515)   
4        (1.36, 0.8046142307473317)     (1.6, 2.413029046674145)   
...                             ...                          ...   
24978      (3.2, 0.623527959941627)   (6.75, 1.9926270191550843)   
24979   (0.87, 0.49699414244829554)  (-8.93, 1.7472400762700504)   
24980  (-7.77, 0.24311442794759922)    (nan, 0.6746466772029548)   
24981   (-9.71, 0.6904470301006087)     (nan, 2.300373557234539)   
24982   (-2.28, 0.5738928485985556)   (7.33, 1.6761784946366087)   

                                 7                              8    \
0       (-9.85, -0.2480810760611386)    (4.17, -0.6294851631557989)   
1      (-0.73, -0.07254274634827973)  (-5.34, -0.39575157861177296)   
2       (9.03, -0.21896896411096659)     (9.27, -0.763867632069748)   
3      (-2.82, -0.13258248871527872)   (6.21, -0.24253065444871197)   
4       (7.04, -0.19299094121059826)     (4.61, -0.680858641849618)   
...                              ...                            ...   
24978  (-8.79, -0.19215694073049008)   (-0.53, -0.5059626424910875)   
24979   (-3.5, -0.20837094970441322)   (5.78, -0.37521320124995156)   
24980    (6.7, -0.03940332790091547)  (-6.75, -0.21533673945471946)   
24981    (4.56, -0.2453851710488554)     (-8.3, -0.543684581788447)   
24982   (2.33, -0.12205208215104468)   (4.56, -0.49355598085106944)   

                                 9                            10   ...  \
0       (-8.98, -0.3519075468089213)  (-4.76, 1.9177414448918497)  ...   
1        (8.88, -0.1918415356149719)   (9.22, 0.9956647957481076)  ...   
2         (nan, -0.3981093775001124)     (nan, 2.120540211156505)  ...   
3         (nan, -0.1486239472833538)   (1.84, 0.8320172792057692)  ...   
4      (-0.44, -0.35407784456994645)    (5.73, 1.884607730576529)  ...   
...                              ...                          ...  ...   
24978  (-8.74, -0.28030070621173964)   (7.23, 1.5231925821825543)  ...   
24979  (-8.11, -0.23107984994234318)    (4.9, 1.2953893671714223)  ...   
24980    (nan, -0.10436079390342022)    (nan, 0.5415891658154692)  ...  

In [ ]:
#  OPTIONAL: Repeat the two points above changing hyper-parameters (i.e., learning rate, number of iterations of SGD, number of latent factors, etc.) 
#  as needed to get good results (you can create multiple validation sets if you want, and run a bootstrap!) [i dont know] 
# *****************

# learning rate, number of iterations of SGD, number of latent factors
# num_iter = 10
# n_latent_factors = 2
# n_rated = 0.1 * len(df)
#  Open the quiz on moodle. After you've done it, make sure you save all the code you used in Github!

# QUIZ

In [ ]:
# quiz(1) You have probably noticed that the jokes dataset needs to be loaded carefully.

# Write below the code you've used to load the dataset, 
# and make sure you load it under a dataframe named 'df' in order for the code checker to work well.
df = pd.read_csv("/content/drive/MyDrive/essex_university/data_science_and_making_data_decition/lab6_recommendation_movie/jester-data-1.csv",header=None)
df = df.replace(99.00, np.nan)
df = df.drop(columns=[0])


In [ ]:
# quiz(2) How many users are there in the Jokes dataset?
print(len(df))


24983


In [ ]:
# quiz(3) When you load the jokes dataset, 
# there's a value that you need to replace with NaNs to indicate that it's not a rating. Which value is this?
# ans:99.00

In [ ]:
# quiz(4)What's the average rating of the worst-rated joke in the Jokes dataset?
# Give your answer with two decimal values (e.g., 1.23).
df.mean().min()


-3.8338796373689923

In [ ]:
# # quiz(5)In the lab instructions you have been asked to modify the function sgd() 
# # provided so that neither the validation nor the test set are used for training.

# # Copy and paste the inner loop of your function below.

# import numpy as np

def sgd(iterations):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    mse_history = []
    for iteration in range(iterations):
        error = []
        for user_id in range(latent_user_preferences.shape[0]):
            for item_id in range(latent_item_features.shape[0]):
                rating = user_ratings[user_id, item_id]
                # if not np.isnan(rating):
                if rating != 99 and not np.isnan(rating):
                    err = train(user_id, item_id, rating)
                    error.append(err)
        mse = (np.array(error) ** 2).mean()   
        if (iteration % 10000) == 0:
            print('Iteration %d/%d:    MSE=%.3f' % (iteration, iterations, mse))
            mse_history.append(mse)
    return mse_history

# np.random.seed(20)

# n_latent_factors = 10
# latent_user_preferences = np.random.random((user_ratings.shape[0], n_latent_factors))
# latent_item_features = np.random.random((user_ratings.shape[1], n_latent_factors))
# hist = sgd(100)

In [ ]:
# quiz(6)In the jokes dataset, what's the rating that user 18942 has given to joke 35?
# Give your answer with two decimal values (e.g., 0.13).

# Please use the following syntax in your code to answer this question: df_jester.iloc[user_x, joke_y].
df.iloc[18942,35]

6.02

In [ ]:
# quiz(7)
# In the movies dataset, what's the loading of Factor 4 for the movie with ID=4469? 
# Give your answer with three decimal values (e.g., 0.123).
# mov_items = pd.read_excel('https://raw.githubusercontent.com/albanda/CE888/master/lab4-recommender/movies_latent_factors.xlsx', sheet_name='Items')
# mov_items

with pd.ExcelFile('/content/drive/MyDrive/essex_university/data_science_and_making_data_decition/lab6_recommendation_movie/movies_latent_factors.xlsx') as reader:
  df_item = pd.read_excel(reader, sheet_name=reader.sheet_names[0])
  df_user = pd.read_excel(reader, sheet_name=reader.sheet_names[1])


df_user[df_user['User'] == 4469]['Factor4']

8   -0.014378
Name: Factor4, dtype: float64

In [ ]:
# quiz(8) In the movies dataset, which of the following IDs corresponds to the movie with the lowest loading of factor 2?
df_item[df_item['Factor2'] == min(df_item['Factor2'])]['Movie ID']


16    122
Name: Movie ID, dtype: int64

In [ ]:
# quiz(9) In the movies dataset, predict the rating that the user with ID 768 will give to the movie with ID 141. 
# Give your answer with two decimal values (e.g., 0.12).
movie_id_clean = df_item[df_item['Movie ID'] == 141]
movie_id_clean.drop('Movie ID',inplace=True,axis=1)
movie_id_clean.drop('Title',inplace=True,axis=1)
movie_id_clean
# df_item

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
18  0.056865  1.573001  0.631437 -0.019755  0.390186 -0.075435 -0.443608   

     Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
18 -0.987379  0.135949 -0.156905  0.442035 -0.284181  0.698186  0.260986   

    Factor15  
18  0.472673

In [ ]:
user_id_clean = df_user[df_user['User'] == 768]
user_id_clean.drop('User',inplace=True,axis=1)
user_id_clean

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
7  0.000819 -0.009229 -0.019228  0.002703  0.012869  0.006655  0.007687   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
7  0.018747  0.014705 -0.009256 -0.010116 -0.010051 -0.002108  0.043223   

   Factor15  
7  -0.00667

In [ ]:
predictions = movie_id_clean.dot(user_id_clean.T)
predictions #answer

7
18 -0.035574

In [ ]:
# quiz(10) In the movies dataset, predict the rating that the user with ID 4373 will give to the movie with ID 786. 
# Give your answer with two decimal values (e.g., 0.12).
movie_id_clean = df_item[df_item['Movie ID'] == 786]
movie_id_clean.drop('Movie ID',inplace=True,axis=1)
movie_id_clean.drop('Title',inplace=True,axis=1)
movie_id_clean

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
62  0.640685  1.199326  0.270392  0.371095  0.479752 -0.144391 -0.752597   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
62  -0.5637  0.439893  0.267137 -0.242001  0.033085 -0.309858  0.005433   

    Factor15  
62  0.256299

In [ ]:
user_id_clean = df_user[df_user['User'] == 4373]
user_id_clean.drop('User',inplace=True,axis=1)
user_id_clean

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1   Factor2   Factor3   Factor4   Factor5  Factor6   Factor7  \
18 -0.13655 -0.089406 -0.235399  0.120585 -0.168168  0.12999 -0.035084   

     Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
18 -0.324028  0.087531   0.04529   0.20785 -0.028972 -0.175184 -0.058283   

    Factor15  
18  0.147797

In [ ]:
predictions = movie_id_clean.dot(user_id_clean.T)
predictions #answer

18
62 -0.012813

In [ ]:
# quiz(11) In the movies dataset, if you had to recommend 3 movies to the user with ID=1882, which ones would you choose?

In [ ]:
# user_id == 1882 and clean
user_id_clean = df_user[df_user['User'] == 1882]
user_id_clean.drop('User', inplace=True, axis=1)
user_id_clean



/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1  Factor2   Factor3   Factor4   Factor5  Factor6   Factor7  \
9 -0.083093 -0.02916  0.013748  0.022716 -0.062732 -0.08067 -0.019723   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
9  0.013253 -0.091305 -0.090687  0.030638 -0.113364 -0.021325  0.181508   

   Factor15  
9  0.022357

In [ ]:
movie_all_items = df_item.copy()
movie_all_items.drop('Title', inplace=True, axis=1)
movie_all_items.drop('Movie ID', inplace=True, axis=1)
movie_all_items



Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
0  -1.521848 -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910   
1  -0.342185 -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887   
2  -2.240888 -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876   
3  -0.634531  2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352   
4   0.517348 -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.159967 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252   
96  1.286288  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971   
97  0.811901 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449   
98  1.161006 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268   
99  1.734008  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377   

     Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
0   0.476710 -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616   
1   0.329516 -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876   
2   1.302036 -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004   
3   0.063841  0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010   
4   0.033626 -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.413082 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580   
96  0.458163  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700   
97 -0.925609 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542   
98 -0.802322 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250   
99 -0.075895  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382   

    Factor15  
0  -0.248806  
1   1.274993  
2  -0.419092  
3  -0.681191  
4  -2.292566  
..       ...  
95  1.017861  
96 -0.487076  
97  0.067790  
98 -0.288130  
99 -0.022599  

[100 rows x 15 columns]

In [ ]:
# predictions = movie_all_items.dot(user_id_clean.T)
predictions = movie_all_items.dot(user_id_clean.T)

predictions

9
0   0.220284
1   0.366293
2  -0.212080
3   0.311120
4   0.249506
..       ...
95  0.230796
96  0.098098
97 -0.105606
98 -0.104062
99 -0.445656

[100 rows x 1 columns]

In [ ]:
# most_2_recommend_movies = predictions.stack().nlargest(2)
most_2_recommend_movies = predictions.sort_values(9,ascending=False)
most_2_recommend_movies

9
51  0.769912
50  0.725877
47  0.609041
21  0.453408
41  0.401888
..       ...
99 -0.445656
26 -0.478864
63 -0.506743
94 -0.511003
90 -0.647339

[100 rows x 1 columns]

In [ ]:
df_item.loc[51]['Title']# ans


'The Matrix Reloaded (2003)'

In [ ]:
df_item.loc[50]['Title']# ans

'The Matrix (1999)'

In [ ]:
df_item.loc[47]['Title']# ans

'Titanic (1997)'

In [ ]:
# quiz(12) In the movies dataset, if you had to recommend 2 movies to the user with ID=3878, which ones would you choose?

user_id_clean = df_user[df_user["User"] == 3878]
user_id_clean.drop("User",inplace=True,axis=1)
user_id_clean
# df_item


/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
6 -0.091462  0.215879 -0.180453  0.085408 -0.321094  0.227947  0.053767   

    Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
6  0.038017  0.097141 -0.139872  0.029253  0.214467   0.18925   0.06599   

   Factor15  
6  0.102776

In [ ]:
movie_all_items = df_item.copy()
movie_all_items.drop("Movie ID",axis=1,inplace=True)
movie_all_items.drop("Title",axis=1,inplace=True)
movie_all_items

Factor1   Factor2   Factor3   Factor4   Factor5   Factor6   Factor7  \
0  -1.521848 -1.038507  2.027269  0.247933 -0.594548  2.513260 -1.848910   
1  -0.342185 -0.296586 -0.385962  2.443297 -1.097015 -0.619465  0.572887   
2  -2.240888 -0.438815 -2.275177  0.614548  0.904469  0.711919 -0.420876   
3  -0.634531  2.186059 -0.066681  0.086197  0.517558 -0.185319 -0.412352   
4   0.517348 -1.456763  0.369161  0.073903 -0.098332 -0.594722  0.828888   
..       ...       ...       ...       ...       ...       ...       ...   
95  0.159967 -0.051123  0.311183  1.841867 -1.952736 -0.836041  0.639252   
96  1.286288  0.004957 -0.157640  2.579640 -0.042687 -0.256582 -0.007971   
97  0.811901 -0.893280  0.668953 -0.885074 -1.070468 -0.973154 -0.037449   
98  1.161006 -0.715613  0.712633 -0.688808 -0.717785 -1.007047 -0.267268   
99  1.734008  0.265436 -0.003391 -0.491754 -0.322739  0.850165 -0.150377   

     Factor8   Factor9  Factor10  Factor11  Factor12  Factor13  Factor14  \
0   0.476710 -0.224146 -0.760681 -0.973915  0.862379  0.403861  1.129616   
1   0.329516 -0.712228  0.323554 -0.561948 -0.142405 -0.564415  0.506876   
2   1.302036 -0.868418 -0.160122  0.633667  0.133138 -0.330276 -2.209004   
3   0.063841  0.075937 -0.577682  0.526803 -1.465557 -0.819682  0.549010   
4   0.033626 -0.707414  0.717877  1.394326 -0.786986  1.429191  0.855746   
..       ...       ...       ...       ...       ...       ...       ...   
95 -0.413082 -0.310868  0.448225 -0.846044 -0.158192 -0.649164  0.045580   
96  0.458163  0.091394  0.323339 -0.862833 -0.508185  0.994535  0.868700   
97 -0.925609 -0.122112 -0.328822 -0.163103 -0.307299  0.642105 -1.355542   
98 -0.802322 -0.249239 -0.540419 -0.291422 -0.240216  0.290714 -1.217250   
99 -0.075895  1.373386  0.934767  0.489299 -0.062678  0.333703 -0.223382   

    Factor15  
0  -0.248806  
1   1.274993  
2  -0.419092  
3  -0.681191  
4  -2.292566  
..       ...  
95  1.017861  
96 -0.487076  
97  0.067790  
98 -0.288130  
99 -0.022599  

[100 rows x 15 columns]

In [ ]:
predictions = movie_all_items.dot(user_id_clean.T)
predictions

6
0   0.619344
1   0.396214
2   0.205784
3  -0.078449
4  -0.686052
..       ...
95  0.363791
96  0.129306
97 -0.376227
98 -0.555636
99  0.193396

[100 rows x 1 columns]

In [ ]:
predictions.sort_values(6,ascending=False)
# .stack().nlargest(2)

6
11  0.928983
90  0.874465
21  0.844621
35  0.817604
9   0.774292
..       ...
86 -1.234513
51 -1.792012
16 -1.980168
14 -1.992433
15 -2.061150

[100 rows x 1 columns]

In [ ]:
df_item.loc[11]['Movie ID']

105

In [ ]:
df_item.loc[90]['Movie ID']

8467